#!/usr/bin/env bash

#  Copyright 2019 Stanislav Senotrusov <stan@senotrusov.com>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

set -o nounset

REPO_VOLUME="/"
REPO_PATH="${HOME}"
REPO_NAME="test-backup"

BORG_PASSPHRASE="hello"
# PASSPHRASE_FILE="/etc/hostname"
KEY_EXPORT_DIR="${HOME}"

# BORG_BASE_DIR=""

RCLONE_REMOTE="onedrive"
RCLONE_PATH="backups"
RCLONE_EXTRA_ARGS="--bwlimit 500k"
# RCLONE_STATE_DIR=""
# RCLONE_CONFIG=""

# LAUNCHD_LABEL=""
# SYSTEMD_NAME=""

# CHECKPOINT=""

make-backup() {
  PREFIX="" FROM_PATH="/usr/share" add-files man
}
